services:
  MySQLdb:
    image: mysql:8.0
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_DATABASE: SatelliteDB
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PWD}
    networks:
      - n2yo_v2
  
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_HOST=MySQLdb
      - PMA_ABSOLUTE_URI=http://localhost:8080/
    networks:
      - n2yo_v2
    depends_on:
      - MySQLdb
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASSWORD}
    networks:
      - n2yo_v2

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - n2yo_v2

volumes:
  db_data:
  grafana_data:
  prometheus_data:

networks:
  n2yo_v2:
    driver: bridge